apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mx2qvxmlf-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/mx2qvxmlf-java-springboot-gitops